'use client'

import React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import type { Contract } from '@/lib/constants'
import { AlertCircle, CheckCircle2, TrendingUp, AlertTriangle, Bot } from 'lucide-react'

export function ExecutiveSummary({ contract }: { contract: Contract }) {
  const summary = contract.summary || {}
  const riskScore = contract.riskScore || 0
  
  const businessSummary = summary.businessSummary || "No business summary available. The contract is currently under analysis or missing critical information."
  const legalSummary = summary.legalSummary || "No legal summary available."
  const financialObligations = summary.financialObligations || ["No specific financial obligations detected."]
  const keyDates = summary.keyDates || ["No critical dates detected."]

  return (
    <div className="p-6 space-y-6 overflow-y-auto h-full">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-serif font-bold tracking-tight">Executive Summary</h2>
          <p className="text-muted-foreground mt-1 flex items-center gap-2">
            <Bot className="w-4 h-4 text-primary" />
            Generated by Multi-Agent AI for {contract.title}
          </p>
        </div>
        <div className="flex flex-col items-end">
          <span className="text-sm text-muted-foreground mb-1">Overall Risk Score</span>
          <div className="flex items-center gap-3">
            <Progress value={riskScore} className="w-32 h-2" />
            <span className={`font-bold ${
              (contract.status === 'review' && riskScore === 0) ? 'text-blue-500 animate-pulse' :
              riskScore > 70 ? 'text-lex-risk-critical' : 
              riskScore > 40 ? 'text-lex-risk-high' : 'text-lex-success'
            }`}>
              {(contract.status === 'review' && riskScore === 0) ? 'Analyzing...' : `${riskScore > 70 ? 'Critical' : riskScore > 40 ? 'High' : 'Low'} (${riskScore})`}
            </span>
          </div>
        </div>
      </div>

      {/* Agents Deployed Section */}
      {contract.clauses && contract.clauses.some(c => c.agent) && (
        <div className="flex items-center gap-3 bg-secondary/20 p-3 rounded-lg border border-border/50">
          <span className="text-sm font-medium text-muted-foreground">Agents Deployed:</span>
          <div className="flex flex-wrap gap-2">
            {Array.from(new Set(contract.clauses.filter(c => c.agent).map(c => c.agent))).map((agent: any) => (
              <Badge key={agent} variant="outline" className="bg-background flex items-center gap-1">
                <Bot className="w-3 h-3 text-primary" /> {agent}
              </Badge>
            ))}
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card className="bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-primary" />
              Business Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground space-y-4">
            <p>{businessSummary}</p>
          </CardContent>
        </Card>

        <Card className="bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-lex-risk-high" />
              Key Legal Risks
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2 text-sm text-muted-foreground">
              <p>{legalSummary}</p>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-lex-success" />
              Financial Obligations
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            <ul className="list-disc pl-5 space-y-2">
              {financialObligations.map((obligation, index) => (
                <li key={index}>{obligation}</li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card className="bg-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-lex-risk-medium" />
              Important Dates
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            <ul className="list-disc pl-5 space-y-2">
              {keyDates.map((dateString, index) => (
                <li key={index}>{dateString}</li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
